
# Global settings applied to the whole site
[build]
  publish = "dist"
  command = "npm run build"

# Redirects for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify Forms processing (critical for form submissions to work)
[[headers]]
  for = "/admin"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Ensures Netlify properly detects the HTML form
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

# 👇 **MOST IMPORTANT: This allows Netlify to process forms correctly**
[[redirects]]
  from = "/forms"
  to = "/forms"
  status = 200
  force = true
